# Basic Python Commands

This jupyter notebook is part of Arizona State University's course CAS 570 (Introduction to Complex Systems Science) and was written by Enrico Borriello. It was last updated September 30, 2024.

____

# Libraries

In [1]:
import numpy as np
import random as rn

**NumPy** is the default Python library for vector and matrix oprations. **Random** contains useful functions to generate pseudo-random numbers. Documentation for these libraries can be found at:

The abbreviations we have defined for numpy and random are useful when using functions from those libraries. For example:

In [2]:
np.mean([1,4,-2,6])

2.25

as opposed to the longer syntax 'numpy.mean([1,4,-2,6])' that we would use if we just imported numpy with 'import numpy'.

'np.mean( )' is a function that evaluates the average of the list of numbers we provide as input.

# Matrices
A numpy matrix can be defined as follows:

In [3]:
A = np.array([[1,2],[0,-1]])
A

array([[ 1,  2],
       [ 0, -1]])

**Numpy** also contains functions to automatically generate matrices of given shapes and with specific characteristics without the need to manually assign all the entries. For example, a 6x6 matrix with all the entries equal to zero can be defined as follows:

In [4]:
N = 6
A = np.zeros((N,N), dtype=int)
A

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

We can select the i-th row of matrix A by typing A[i]. Remeber that python numbering starts from zero. Therefore the first row of A is A[0], the second row is A[1], etc.

In [5]:
A[2]

array([0, 0, 0, 0, 0, 0])

We can select element j of column i of matrix A by typing A[i][j]

In [6]:
A[2][3]

0

We can achieve the same result with

In [7]:
A[2,3]

0

Additionally, we can retrieve all the elements of a given row/column replacing its index with ':'

In [8]:
A[2,:]

array([0, 0, 0, 0, 0, 0])

In [9]:
A[:,3]

array([0, 0, 0, 0, 0, 0])

We can change the value of an entry of a matrix by just reassigning its value:

In [10]:
A[2,3] = 1

We can check the result

In [11]:
A

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [12]:
A[2,:]

array([0, 0, 0, 1, 0, 0])

In [13]:
A[:,3]

array([0, 0, 1, 0, 0, 0])

## Loops

We can use a **for** loop to iterate one or more operations: 

In [14]:
for i in [0,1,2,3]:
    print(i)

0
1
2
3


Notice that the instruction that we want to perform begins with an indentation. 

There is a more compact way to refer to a range of consecutive integers:

In [15]:
for i in range(4):
    print(i)

0
1
2
3


Notice that the numbering starts at zero and ends at 4-1 = 3. Therfore, with range(4), we refer to 4 consecutive integers, the first one being zero.

Here's another example, showing that we can perform more than one instruction per step:

In [16]:
for i in range(10):
    x = 2*i
    print(x)

0
2
4
6
8
10
12
14
16
18


(The four basic operations in Python are '+', '-', '*', '/'.)

The **for** loop can also be used to easily generate lists:

In [17]:
[2*i for i in range(10)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

Here's an example not involving numbers:

In [18]:
[character for character in 'word']

['w', 'o', 'r', 'd']

If you're wondering about the previous output, python sees words as lists of charaters.

### Nested loops

It is possible to have a for loop as an instruction inside another for loop:

In [19]:
N = 3
for i in range(N):
    for j in range(N):
        print(i*j)

0
0
0
0
1
2
0
2
4


# If condition
It is possible to perform an instructio only if a certain condition is met. For example:

In [20]:
if rn.random() < 0.6:
    print('random number less than 0.6')

Execute the previous command several times. It will print an output only about 60% of times. The reason is that 'rn.random( )' generates a random number between zero and 1. Therefore, it will be less than 1 only 60% of times.

Common conditions that can be used with 'if' are:

'<' less than

'>' greater than

'==' equal to

'!=' not equal to

It is possible to have an if condition nested within a for loop: 

In [21]:
p = 0.5
for i in range(10):
    x = rn.random() 
    if x < p:
        print(i,x)

0 0.39012768901139194
2 0.3383033739795501
7 0.13380869975490417
8 0.23922316137399058
9 0.3920746575375105


(Notice that 'print( )' can have more than one input.)

Notice that, if the condition is not satisfied, the instructions are not executed, and the xcecution leaves the if statement. Sometimes, it could be useful to provide an alternative set of instructions for when the conditon is not satisfied. This is done using 'if' and 'else' (not nested):

In our previous example:

In [22]:
if rn.random() < 0.6:
    print('random number less than 0.6')
else:
    print('random number greater than 0.6')

random number less than 0.6


# Functions
'print( )', 'np.random( )', 'np.mean( )' etc. are **functions**. We can easily define new, custom functions as in the following example:

In [23]:
def square(x):
    return x*x

In [24]:
square(10)

100

A function can have any number of inputs. It can also contain any number of intermediate instructions between 'def' and 'return'. For example, here's a function that calculates the volume of a cylinder of radius r and height h:

In [25]:
def cylinder_volume(r,h):
    base_area = np.pi*r*r 
    # np.pi = 3.14... 
    # everything following # in a line is not executed by python, 
    # and can be used to add comments to the code
    volume = base_area*h
    return volume

In [26]:
cylinder_volume(2,10)

125.66370614359172

A function can contain loops and if conditions, nested or not.